# Generated by Django 4.0 on 2021-12-15 21:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 15, 21, 9, 33, 619931, tzinfo=utc)),
        ),
    ]
