# Generated by Django 4.0 on 2021-12-15 21:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_alter_task_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateField(verbose_name=datetime.datetime(2021, 12, 15, 21, 11, 29, 200387, tzinfo=utc)),
        ),
    ]
