# Generated by Django 4.0 on 2021-12-15 21:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_alter_task_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 15, 21, 12, 35, 453472, tzinfo=utc)),
        ),
    ]
