# Generated by Django 4.0 on 2021-12-18 19:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_alter_task_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 18, 19, 26, 32, 238190, tzinfo=utc)),
        ),
    ]
